import Project1 from '@/assets/projects/1/Project1';
import Project2 from '@/assets/projects/2/Project2';
import Project3 from '@/assets/projects/3/Project3';
import Project4 from '@/assets/projects/4/Project4';
import Project5 from '@/assets/projects/5/Project5';
import Project6 from '@/assets/projects/6/Project6';
import Project7 from '@/assets/projects/7/Project7';
import Project8 from '@/assets/projects/8/Project8';

export default {
    name: "ProjectData",
    data(){
        return{
            projectData: [
                {
                    id:1,
                    title: {ZH:'无尽长夜',EN:'ENDLESS NIGHT'},
                    period: 2017,
                    category:{ZH:'游戏设计',EN:'Game Design'},
                    categoryIndex:4,
                    dataSrc: require('@/assets/projects/1/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/1/details1.png'),
                        require('@/assets/projects/1/details2.gif'),
                        require('@/assets/projects/1/details3.png'),
                        require('@/assets/projects/1/details4.png'),
                        require('@/assets/projects/1/details5.png'),
                    ],
                    details:Project1,
                },
                {
                    id:2,
                    title: {ZH:'她',EN:'SHE'},
                    period: 2017,
                    category:{ZH:'视觉创意',EN:'Visual Creativity'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/2/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/2/details1.png'),
                        require('@/assets/projects/2/details2.png'),
                        require('@/assets/projects/2/details3.png'),
                        require('@/assets/projects/2/details4.png'),
                        require('@/assets/projects/2/details5.png'),
                        require('@/assets/projects/2/details6.png'),
                        require('@/assets/projects/2/details7.png'),
                    ],
                    details:Project2,
                },
                {
                    id:3,
                    title: {ZH:'懿翼茶',EN:'Yiyi Tea'},
                    period: 2019,
                    category:{ZH:'包装设计',EN:'Packaging Design'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/3/preview.png'),
                    dataHover: require('@/assets/projects/3/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/3/details1.png'),
                        require('@/assets/projects/3/details3.png'),
                        require('@/assets/projects/3/details4.png'),
                        require('@/assets/projects/3/details5.png'),
                        require('@/assets/projects/3/details6.png'),
                    ],
                    details:Project3,
                },
                {
                    id:4,
                    title: {ZH:'致新医药',EN:'ZHI XIN PHARMA'},
                    period: 2020,
                    category:{ZH:'动态视觉识别',EN:'Dynamic Visual Identify'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/4/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/4/details1.png'),
                        require('@/assets/projects/4/details2.gif'),
                        require('@/assets/projects/4/details3-1.png'),
                        require('@/assets/projects/4/details3-2.png'),
                        require('@/assets/projects/4/details3-3.png'),
                        require('@/assets/projects/4/details3-4.png'),
                        require('@/assets/projects/4/details3-5.png'),
                        require('@/assets/projects/4/details3-6.png'),
                        require('@/assets/projects/4/details4.png'),
                        require('@/assets/projects/4/details5.png'),
                        require('@/assets/projects/4/details6.png'),
                        require('@/assets/projects/4/details7.png'),
                        require('@/assets/projects/4/details8.png'),
                        require('@/assets/projects/4/details9.png'),
                        require('@/assets/projects/4/details10.png'),
                        require('@/assets/projects/4/details11.png'),
                        require('@/assets/projects/4/details12.png'),
                    ],
                    details:Project4,
                },
                {
                    id:5,
                    title: {ZH:'随异文化',EN:'SEEM DESIGN'},
                    period: 2020,
                    category:{ZH:'动态视觉识别',EN:'Dynamic Visual Identify'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/5/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/5/details1.png'),
                        require('@/assets/projects/5/details2.svg'),
                        require('@/assets/projects/5/details3.gif'),
                        require('@/assets/projects/5/details4.gif'),
                        require('@/assets/projects/5/details5.png'),
                        require('@/assets/projects/5/details6.png'),
                        require('@/assets/projects/5/details8.png'),
                        require('@/assets/projects/5/details9.png'),
                    ],
                    details:Project5,
                },
                {
                    id:6,
                    title: {ZH:'RaceFit 易起动',EN:'RaceFit CORE Fitness'},
                    period: 2021,
                    category: {ZH:'用户体验',EN:'User Experience'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/6/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/6/details1.svg'),
                        require('@/assets/projects/6/details2.svg'),
                        require('@/assets/projects/6/details3.svg'),
                        require('@/assets/projects/6/details1-EN.svg'),
                        require('@/assets/projects/6/details2-EN.svg'),
                        require('@/assets/projects/6/details3-EN.svg'),
                        require('@/assets/projects/6/details4.png'),
                        require('@/assets/projects/6/details5.png'),
                        require('@/assets/projects/6/details6.png'),
                        require('@/assets/projects/6/details7.png'),
                        require('@/assets/projects/6/details8.png'),
                        require('@/assets/projects/6/details9.png'),
                        require('@/assets/projects/6/details10.svg'),
                        require('@/assets/projects/6/details11.svg'),
                        require('@/assets/projects/6/details12.svg'),
                        require('@/assets/projects/6/details10-EN.svg'),
                        require('@/assets/projects/6/details11-EN.svg'),
                        require('@/assets/projects/6/details12-EN.svg'),
                        require('@/assets/projects/6/details13.svg'),
                        require('@/assets/projects/6/details14.svg'),
                        require('@/assets/projects/6/details14-EN.svg'),
                        require('@/assets/projects/6/details15.svg'),
                        require('@/assets/projects/6/details16.png'),
                        require('@/assets/projects/6/details17.png'),
                        require('@/assets/projects/6/details18.svg'),
                        require('@/assets/projects/6/details18-EN.svg'),
                        require('@/assets/projects/6/details19.svg'),
                        require('@/assets/projects/6/details19-EN.svg'),
                        require('@/assets/projects/6/app01.png'),
                        require('@/assets/projects/6/app02.png'),
                        require('@/assets/projects/6/app03.png'),
                        require('@/assets/projects/6/app04.png'),
                        require('@/assets/projects/6/app05.png'),
                        require('@/assets/projects/6/app06.png'),
                        require('@/assets/projects/6/app07.png'),
                    ],
                    details:Project6,
                },
                {
                    id:7,
                    title: {ZH:'RaceFit CORE',EN:'RaceFit CORE'},
                    period: 2019,
                    category: {ZH:'产品设计',EN:'Product Design'},
                    categoryIndex:3,
                    dataSrc: require('@/assets/projects/7/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/7/band01.png'),
                        require('@/assets/projects/7/band03.png'),
                        require('@/assets/projects/7/band04.png'),
                        require('@/assets/projects/7/details1.svg'),
                        require('@/assets/projects/7/details2.png'),
                        require('@/assets/projects/7/details3.png'),
                        require('@/assets/projects/7/details4.png'),
                        require('@/assets/projects/7/strap1.png'),
                        require('@/assets/projects/7/strap2.png'),
                        require('@/assets/projects/7/strap3.png'),
                        require('@/assets/projects/7/strap4.png'),
                        require('@/assets/projects/7/strap5.png'),
                        require('@/assets/projects/7/strap6.png'),
                        require('@/assets/projects/7/suit01.svg'),
                        require('@/assets/projects/7/suit02.png'),
                        require('@/assets/projects/7/suit03.png'),
                        require('@/assets/projects/7/web-summit.png'),
                        require('@/assets/projects/7/what-is-a-core.png'),
                        require('@/assets/projects/7/reddot.svg'),
                    ],
                    details:Project7,
                },
                {
                    id:8,
                    title: {ZH:'小仓署',EN:'Hamster'},
                    period: 2019,
                    category: {ZH:'服务设计',EN:'Service Design'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/8/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/8/details1.png'),
                        require('@/assets/projects/8/details2.png'),
                        require('@/assets/projects/8/details3.png'),
                        require('@/assets/projects/8/details4.png'),
                        require('@/assets/projects/8/details5.png'),
                        require('@/assets/projects/8/app1.png'),
                        require('@/assets/projects/8/app2.png'),
                        require('@/assets/projects/8/app3.png'),
                        require('@/assets/projects/8/app4.png'),
                        require('@/assets/projects/8/app5.png'),
                        require('@/assets/projects/8/app6.png'),
                    ],
                    details:Project8,
                },
            ],
            projectCategories:[
                {id:1,ZH:'体验',EN:'Experience'},
                {id:2,ZH:'视觉',EN:'Visual'},
                {id:3,ZH:'产品',EN:'Product'},
                {id:4,ZH:'其他',EN:'Others'}
            ]
        }
    },
}
