import Project4 from '@/assets/projects/4/Project4';
import Project5 from '@/assets/projects/5/Project5';
import Project6 from '@/assets/projects/6/Project6';
import Project9 from '@/assets/projects/9/Project9';

export default {
    name: "ProjectData",
    data(){
        return{
            projectData: [
                {
                    id:1,
                    title: {ZH:'致新医药',EN:'Zhi Xin Pharma'},
                    period: 2020,
                    category:{ZH:'视觉识别',EN:'Visual identify'},
                    skills:{ZH:'品牌思维 \n 视觉识别系统',EN:'Branding thinking \n Visual identity system'},
                    teams:{ZH:'Adobe Illustrator \n Blender',EN:'Adobe Illustrator \n Blender'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/4/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/4/details1.png'),
                        require('@/assets/projects/4/details2.gif'),
                        require('@/assets/projects/4/details3-1.png'),
                        require('@/assets/projects/4/details3-2.png'),
                        require('@/assets/projects/4/details3-3.png'),
                        require('@/assets/projects/4/details3-4.png'),
                        require('@/assets/projects/4/details3-5.png'),
                        require('@/assets/projects/4/details3-6.png'),
                        require('@/assets/projects/4/details4.png'),
                        require('@/assets/projects/4/details5.png'),
                        require('@/assets/projects/4/details6.png'),
                        require('@/assets/projects/4/details7.png'),
                        require('@/assets/projects/4/details8.png'),
                        require('@/assets/projects/4/details9.png'),
                        require('@/assets/projects/4/details10.png'),
                        require('@/assets/projects/4/details11.png'),
                        require('@/assets/projects/4/details12.png'),
                    ],
                    details:Project4,
                    relatedID:[2]
                },
                {
                    id:2,
                    title: {ZH:'随异文化',EN:'SEEM Design'},
                    period: 2020,
                    category:{ZH:'视觉识别',EN:'Visual identify'},
                    skills:{ZH:'品牌思维 \n 视觉识别系统',EN:'Branding thinking \n Visual identity system'},
                    teams:{ZH:'Adobe Illustrator \n p5.js',EN:'Adobe Illustrator \n p5.js'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/5/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/5/details1.png'),
                        require('@/assets/projects/5/details2.svg'),
                        require('@/assets/projects/5/details3.gif'),
                        require('@/assets/projects/5/details4.gif'),
                        require('@/assets/projects/5/details5.png'),
                        require('@/assets/projects/5/details6.png'),
                        require('@/assets/projects/5/details8.png'),
                        require('@/assets/projects/5/details9.png'),
                    ],
                    details:Project5,
                    relatedID:[3]
                },
                {
                    id:3,
                    title: {ZH:'RaceFit 易起动',EN:'RaceFit CORE Fitness'},
                    period: 2021,
                    category: {ZH:'产品设计',EN:'Product design'},
                    skills:{ZH:'用户研究 \n 系统思维 \n 产品思维 \n 产品设计 \n 平面设计 \n 动态图形 \n 角色动画 \n 用户测试',EN:'User research \n System thinking \n Product thinking \n Product design \n Graphic design \n Motion graphic \n Animation \n User testing'},
                    teams:{ZH:'Figma \n Proropie \n Blender \n Adobe Illustrator',EN:'Figma \n Proropie \n Blender \n Adobe Illustrator'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/6/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/6/details1.svg'),
                        require('@/assets/projects/6/details2.svg'),
                        require('@/assets/projects/6/details3.svg'),
                        require('@/assets/projects/6/details1-EN.svg'),
                        require('@/assets/projects/6/details2-EN.svg'),
                        require('@/assets/projects/6/details3-EN.svg'),
                        require('@/assets/projects/6/details4.png'),
                        require('@/assets/projects/6/details5.png'),
                        require('@/assets/projects/6/details6.png'),
                        require('@/assets/projects/6/details10.svg'),
                        require('@/assets/projects/6/details10-EN.svg'),
                        require('@/assets/projects/6/details11.svg'),
                        require('@/assets/projects/6/details11-EN.svg'),
                        require('@/assets/projects/6/details12.svg'),
                        require('@/assets/projects/6/details13.svg'),
                        require('@/assets/projects/6/details14.svg'),
                        require('@/assets/projects/6/details14-EN.svg'),
                        require('@/assets/projects/6/details15.svg'),
                        require('@/assets/projects/6/details15-EN.svg'),
                        require('@/assets/projects/6/details16.svg'),
                        require('@/assets/projects/6/details16-EN.svg'),
                        require('@/assets/projects/6/details17.svg'),
                        require('@/assets/projects/6/details17-EN.svg'),
                        require('@/assets/projects/6/flow.svg'),
                        require('@/assets/projects/6/flow-EN.svg'),
                        require('@/assets/projects/6/ia.svg'),
                        require('@/assets/projects/6/ia-EN.svg'),
                        require('@/assets/projects/6/animation-v1.gif'),
                        require('@/assets/projects/6/animation-v2.gif'),
                        require('@/assets/projects/6/animations-collection.gif'),
                        require('@/assets/projects/6/background.png'),
                        require('@/assets/projects/6/brandcolor-EN.svg'),
                        require('@/assets/projects/6/brandcolor.svg'),
                        require('@/assets/projects/6/calibration.gif'),
                        require('@/assets/projects/6/detailpage1.png'),
                        require('@/assets/projects/6/detailpage2.png'),
                        require('@/assets/projects/6/detailpage3.png'),
                        require('@/assets/projects/6/lookingforcores.gif'),
                        require('@/assets/projects/6/module1.svg'),
                        require('@/assets/projects/6/module2.svg'),
                        require('@/assets/projects/6/module3.svg'),
                        require('@/assets/projects/6/module4.svg'),
                        require('@/assets/projects/6/training.gif'),
                        require('@/assets/projects/6/stylefor4types-EN.svg'),
                        require('@/assets/projects/6/stylefor4types.svg'),
                        require('@/assets/projects/6/operationdesign.png'),

                    ],
                    details:Project6,
                    relatedID:[4]
                },
                {
                    id:4,
                    title: {ZH:'Azure 内容安全',EN:'Azure Content Safety'},
                    period: 2023,
                    category: {ZH:'产品设计',EN:'Product design'},
                    skills:{ZH:'产品设计 \n 用户测试',EN:'Product design \n User testing'},
                    teams:{ZH:'Figma',EN:'Figma'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/9/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                    ],
                    details:Project9,
                    relatedID:[1],
                },
            ],
            projectCategories:[
                {id:1,ZH:'产品',EN:'Product'},
                {id:2,ZH:'视觉',EN:'Visual'},
                // {id:3,ZH:'实验',EN:'Playground'},
            ]
        }
    },
}
