import Project1 from '@/assets/projects/1/Project1';
import Project2 from '@/assets/projects/2/Project2';
import Project3 from '@/assets/projects/3/Project3';
import Project4 from '@/assets/projects/4/Project4';
import Project5 from '@/assets/projects/5/Project5';
import Project6 from '@/assets/projects/6/Project6';
import Project7 from '@/assets/projects/7/Project7';
import Project8 from '@/assets/projects/8/Project8';
import Project9 from '@/assets/projects/9/Project9';
import Project10 from '@/assets/projects/10/Project10';

export default {
    name: "ProjectData",
    data(){
        return{
            projectData: [
                {
                    id:1,
                    title: {ZH:'无尽长夜',EN:'Endless Darkness'},
                    period: 2017,
                    category:{ZH:'独立游戏',EN:'Indie game'},
                    skills:{ZH:'游戏设计 \n 交互设计',EN:'Game design \n Interaction design'},
                    teams:{ZH:'Solo',EN:'Solo'},
                    categoryIndex:3,
                    dataSrc: require('@/assets/projects/1/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/1/details1.png'),
                        require('@/assets/projects/1/details2.gif'),
                        require('@/assets/projects/1/details3.png'),
                        require('@/assets/projects/1/details4.png'),
                        require('@/assets/projects/1/details5.png'),
                    ],
                    details:Project1,
                    relatedID:[10],
                },
                {
                    id:2,
                    title: {ZH:'她',EN:'SHE'},
                    period: 2017,
                    category:{ZH:'视觉创意',EN:'Visual creativity'},
                    skills:{ZH:'3D 渲染 ',EN:'3D rendering'},
                    teams:{ZH:'Solo',EN:'Solo'},
                    categoryIndex:3,
                    dataSrc: require('@/assets/projects/2/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/2/details1.png'),
                        require('@/assets/projects/2/details2.png'),
                        require('@/assets/projects/2/details3.png'),
                        require('@/assets/projects/2/details4.png'),
                        require('@/assets/projects/2/details5.png'),
                        require('@/assets/projects/2/details6.png'),
                        require('@/assets/projects/2/details7.png'),
                    ],
                    details:Project2,
                    relatedID:[3]
                },
                {
                    id:3,
                    title: {ZH:'懿翼茶',EN:'Yiyi Tea'},
                    period: 2019,
                    category:{ZH:'包装设计',EN:'Packaging design'},
                    skills:{ZH:'平面设计',EN:'Graphic design'},
                    teams:{ZH:'Solo',EN:'Solo'},
                    categoryIndex:3,
                    dataSrc: require('@/assets/projects/3/preview.png'),
                    dataHover: require('@/assets/projects/3/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/3/details1.png'),
                        require('@/assets/projects/3/details3.png'),
                        require('@/assets/projects/3/details4.png'),
                        require('@/assets/projects/3/details5.png'),
                        require('@/assets/projects/3/details6.png'),
                    ],
                    details:Project3,
                    relatedID:[2]
                },
                {
                    id:4,
                    title: {ZH:'致新医药',EN:'Zhi Xin Pharma'},
                    period: 2020,
                    category:{ZH:'视觉识别',EN:'Visual identify'},
                    skills:{ZH:'品牌思维 \n 视觉识别系统',EN:'Branding thinking \n Visual identity system'},
                    teams:{ZH:'Solo',EN:'Solo'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/4/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/4/details1.png'),
                        require('@/assets/projects/4/details2.gif'),
                        require('@/assets/projects/4/details3-1.png'),
                        require('@/assets/projects/4/details3-2.png'),
                        require('@/assets/projects/4/details3-3.png'),
                        require('@/assets/projects/4/details3-4.png'),
                        require('@/assets/projects/4/details3-5.png'),
                        require('@/assets/projects/4/details3-6.png'),
                        require('@/assets/projects/4/details4.png'),
                        require('@/assets/projects/4/details5.png'),
                        require('@/assets/projects/4/details6.png'),
                        require('@/assets/projects/4/details7.png'),
                        require('@/assets/projects/4/details8.png'),
                        require('@/assets/projects/4/details9.png'),
                        require('@/assets/projects/4/details10.png'),
                        require('@/assets/projects/4/details11.png'),
                        require('@/assets/projects/4/details12.png'),
                    ],
                    details:Project4,
                    relatedID:[5]
                },
                {
                    id:5,
                    title: {ZH:'随异文化',EN:'SEEM Design'},
                    period: 2020,
                    category:{ZH:'视觉识别',EN:'Visual identify'},
                    skills:{ZH:'品牌思维 \n 视觉识别系统',EN:'Branding thinking \n Visual identity system'},
                    teams:{ZH:'Solo',EN:'Solo'},
                    categoryIndex:2,
                    dataSrc: require('@/assets/projects/5/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/5/details1.png'),
                        require('@/assets/projects/5/details2.svg'),
                        require('@/assets/projects/5/details3.gif'),
                        require('@/assets/projects/5/details4.gif'),
                        require('@/assets/projects/5/details5.png'),
                        require('@/assets/projects/5/details6.png'),
                        require('@/assets/projects/5/details8.png'),
                        require('@/assets/projects/5/details9.png'),
                    ],
                    details:Project5,
                    relatedID:[4]
                },
                {
                    id:6,
                    title: {ZH:'RaceFit 易起动',EN:'RaceFit CORE Fitness'},
                    period: 2021,
                    category: {ZH:'产品设计',EN:'Product design'},
                    skills:{ZH:'用户研究 \n 系统思维 \n 产品思维 \n 产品设计 \n 平面设计 \n 动态图形 \n 角色动画 \n 用户测试',EN:'User research \n System thinking \n Product thinking \n Product design \n Graphic design \n Motion graphic \n Animation \n User testing'},
                    teams:{ZH:'Graham, CEO\nDennis Poon, CXO\nKeith, Algo Lead\nCyrus, Sofeware Lead\nAndy, Hardware Lead\n Zidong, Design Lead' ,EN:'Graham, CEO\nDennis Poon, CXO\nKeith, Algo Lead\nCyrus, Sofeware Lead\nAndy, Hardware Lead\n Zidong, Design Lead'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/6/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/6/details1.svg'),
                        require('@/assets/projects/6/details2.svg'),
                        require('@/assets/projects/6/details3.svg'),
                        require('@/assets/projects/6/details1-EN.svg'),
                        require('@/assets/projects/6/details2-EN.svg'),
                        require('@/assets/projects/6/details3-EN.svg'),
                        require('@/assets/projects/6/details4.png'),
                        require('@/assets/projects/6/details5.png'),
                        require('@/assets/projects/6/details6.png'),
                        require('@/assets/projects/6/details10.svg'),
                        require('@/assets/projects/6/details10-EN.svg'),
                        require('@/assets/projects/6/details11.svg'),
                        require('@/assets/projects/6/details11-EN.svg'),
                        require('@/assets/projects/6/details12.svg'),
                        require('@/assets/projects/6/details13.svg'),
                        require('@/assets/projects/6/details14.svg'),
                        require('@/assets/projects/6/details14-EN.svg'),
                        require('@/assets/projects/6/details15.svg'),
                        require('@/assets/projects/6/details15-EN.svg'),
                        require('@/assets/projects/6/details16.svg'),
                        require('@/assets/projects/6/details16-EN.svg'),
                        require('@/assets/projects/6/details17.svg'),
                        require('@/assets/projects/6/details17-EN.svg'),
                        require('@/assets/projects/6/flow.svg'),
                        require('@/assets/projects/6/flow-EN.svg'),
                        require('@/assets/projects/6/ia.svg'),
                        require('@/assets/projects/6/ia-EN.svg'),
                        require('@/assets/projects/6/animation-v1.gif'),
                        require('@/assets/projects/6/animation-v2.gif'),
                        require('@/assets/projects/6/animations-collection.gif'),
                        require('@/assets/projects/6/background.png'),
                        require('@/assets/projects/6/brandcolor-EN.svg'),
                        require('@/assets/projects/6/brandcolor.svg'),
                        require('@/assets/projects/6/calibration.gif'),
                        require('@/assets/projects/6/detailpage1.png'),
                        require('@/assets/projects/6/detailpage2.png'),
                        require('@/assets/projects/6/detailpage3.png'),
                        require('@/assets/projects/6/lookingforcores.gif'),
                        require('@/assets/projects/6/module1.svg'),
                        require('@/assets/projects/6/module2.svg'),
                        require('@/assets/projects/6/module3.svg'),
                        require('@/assets/projects/6/module4.svg'),
                        require('@/assets/projects/6/training.gif'),
                        require('@/assets/projects/6/stylefor4types-EN.svg'),
                        require('@/assets/projects/6/stylefor4types.svg'),
                        require('@/assets/projects/6/operationdesign.png'),

                    ],
                    details:Project6,
                    relatedID:[7,8,9]
                },
                {
                    id:7,
                    title: {ZH:'Microsoft Teams Updates App',EN:'Microsoft Teams Updates App'},
                    period: 2023,
                    category: {ZH:'工业设计',EN:'Product design'},
                    skills:{ZH:'产品思维 \n 产品设计 \n 组件库管理 \n 用户测试',EN:'Product thinking \n Product design \n Components library \n User testing'},
                    teams:{ZH:'Dingyi Yu, PM,\n Yuxiang Zhou, PM,\n Sikang Li, UX designer,\n Zidong Chen, UX designer \n Updates Dev team',EN:'Dingyi Yu,\n PM, Yuxiang Zhou, PM,\n Sikang Li, UX designer,\n Zidong Chen, UX designer \n Updates Dev team'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/7/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/7/Updates in Microsoft Teams blog - Teaser image.png')
                    ],
                    details:Project7,
                    relatedID:[6]
                },
                {
                    id:8,
                    title: {ZH:'小仓署',EN:'Hamster'},
                    period: 2019,
                    category: {ZH:'产品设计',EN:'Product design'},
                    skills:{ZH:'系统思维 \n 服务设计 \n 产品设计',EN:'System thinking \n Service design \n Product design'},
                    teams:{ZH:'Zidong, Team lead\nXiaoyu Wang, UI design\nYidi Zhao, UI design\nPeiyi Cai, Service design',EN:'Zidong, Team lead\nXiaoyu Wang, UI design\nYidi Zhao, UI design\nPeiyi Cai, Service design'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/8/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/8/details1.png'),
                        require('@/assets/projects/8/details2.png'),
                        require('@/assets/projects/8/details3.png'),
                        require('@/assets/projects/8/details4.png'),
                        require('@/assets/projects/8/details5.png'),
                        require('@/assets/projects/8/app1.png'),
                        require('@/assets/projects/8/app2.png'),
                        require('@/assets/projects/8/app3.png'),
                        require('@/assets/projects/8/app4.png'),
                        require('@/assets/projects/8/app5.png'),
                        require('@/assets/projects/8/app6.png'),
                    ],
                    details:Project8,
                    relatedID:[9,6]
                },
                {
                    id:9,
                    title: {ZH:'Azure 内容安全',EN:'Azure Content Safety'},
                    period: 2023,
                    category: {ZH:'产品设计',EN:'Product design'},
                    skills:{ZH:'产品设计 \n 用户测试',EN:'Product design \n User testing'},
                    teams:{ZH:'Louise Han, PM\nRandy Winjum, UX designer\nMeltem Gurcay-Morris, User researcher\nZidong, UX designer',EN:'Figma'},
                    categoryIndex:1,
                    dataSrc: require('@/assets/projects/9/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                    ],
                    details:Project9,
                    relatedID:[8,6],
                },
                {
                    id:10,
                    title: {ZH:'凑个七',EN:'Add to seven'},
                    headline: {ZH:'七是一个充满神秘的数字',EN:'7 is a number full of mystery.'},
                    category: {ZH:'独立游戏',EN:'Indie game'},
                    skills:{ZH:'游戏设计 \n 交互设计 \n 用户测试',EN:'Game design \n Interaction design \n User testing'},
                    teams:{ZH:'Figma \n Wechat developer teams',EN:'Figma \n Wechat developer teams'},
                    period: 2022,
                    categoryIndex:3,
                    dataSrc: require('@/assets/projects/10/preview.png'),
                    isShowcases: true,
                    detailsImages:[
                        require('@/assets/projects/10/qrcode.png'),
                    ],
                    details:Project10,
                    relatedID:[1],
                },
            ],
            projectCategories:[
                {id:1,ZH:'产品',EN:'Product'},
                {id:2,ZH:'品牌',EN:'Brand'},
                {id:3,ZH:'实验',EN:'Playground'},
            ]
        }
    },
}
